/// All 32 toy types from reference screenshot grid (row-major).
enum ToyType {
  teddy,
  duck,
  frog,
  rocket,
  rabbit,
  panda,
  cat,
  owl,
  heart,
  football,
  star,
  penguin,
  cactus,
  grapes,
  apple,
  rainbowRings,
  car,
  chick,
  pig,
  whale,
  unicorn,
  dinosaur,
  burger,
  fries,
  sunglasses,
  iceCream,
  dice,
  robot,
  basketball,
  flower,
  octopus,
  bee,
}

extension ToyTypeX on ToyType {
  String get assetName => switch (this) {
        ToyType.teddy => 'teddy',
        ToyType.duck => 'duck',
        ToyType.frog => 'frog',
        ToyType.rocket => 'rocket',
        ToyType.rabbit => 'rabbit',
        ToyType.panda => 'panda',
        ToyType.cat => 'cat',
        ToyType.owl => 'owl',
        ToyType.heart => 'heart',
        ToyType.football => 'football',
        ToyType.star => 'star',
        ToyType.penguin => 'penguin',
        ToyType.cactus => 'cactus',
        ToyType.grapes => 'grapes',
        ToyType.apple => 'apple',
        ToyType.rainbowRings => 'rainbow_rings',
        ToyType.car => 'car',
        ToyType.chick => 'chick',
        ToyType.pig => 'pig',
        ToyType.whale => 'whale',
        ToyType.unicorn => 'unicorn',
        ToyType.dinosaur => 'dinosaur',
        ToyType.burger => 'burger',
        ToyType.fries => 'fries',
        ToyType.sunglasses => 'sunglasses',
        ToyType.iceCream => 'ice_cream',
        ToyType.dice => 'dice',
        ToyType.robot => 'robot',
        ToyType.basketball => 'basketball',
        ToyType.flower => 'flower',
        ToyType.octopus => 'octopus',
        ToyType.bee => 'bee',
      };

  String get assetPath => 'assets/images/premium/toys/$assetName.png';

  String get emoji => switch (this) {
        ToyType.teddy => '🧸',
        ToyType.duck => '🦆',
        ToyType.frog => '🐸',
        ToyType.rocket => '🚀',
        ToyType.rabbit => '🐰',
        ToyType.panda => '🐼',
        ToyType.cat => '🐱',
        ToyType.owl => '🦉',
        ToyType.heart => '❤️',
        ToyType.football => '⚽',
        ToyType.star => '⭐',
        ToyType.penguin => '🐧',
        ToyType.cactus => '🌵',
        ToyType.grapes => '🍇',
        ToyType.apple => '🍎',
        ToyType.rainbowRings => '🌈',
        ToyType.car => '🚗',
        ToyType.chick => '🐤',
        ToyType.pig => '🐷',
        ToyType.whale => '🐳',
        ToyType.unicorn => '🦄',
        ToyType.dinosaur => '🦖',
        ToyType.burger => '🍔',
        ToyType.fries => '🍟',
        ToyType.sunglasses => '😎',
        ToyType.iceCream => '🍦',
        ToyType.dice => '🎲',
        ToyType.robot => '🤖',
        ToyType.basketball => '🏀',
        ToyType.flower => '🌼',
        ToyType.octopus => '🐙',
        ToyType.bee => '🐝',
      };

  String get label => switch (this) {
        ToyType.teddy => 'Teddy',
        ToyType.duck => 'Duck',
        ToyType.frog => 'Frog',
        ToyType.rocket => 'Rocket',
        ToyType.rabbit => 'Rabbit',
        ToyType.panda => 'Panda',
        ToyType.cat => 'Cat',
        ToyType.owl => 'Owl',
        ToyType.heart => 'Heart',
        ToyType.football => 'Ball',
        ToyType.star => 'Star',
        ToyType.penguin => 'Penguin',
        ToyType.cactus => 'Cactus',
        ToyType.grapes => 'Grapes',
        ToyType.apple => 'Apple',
        ToyType.rainbowRings => 'Rings',
        ToyType.car => 'Car',
        ToyType.chick => 'Chick',
        ToyType.pig => 'Pig',
        ToyType.whale => 'Whale',
        ToyType.unicorn => 'Unicorn',
        ToyType.dinosaur => 'Dino',
        ToyType.burger => 'Burger',
        ToyType.fries => 'Fries',
        ToyType.sunglasses => 'Shades',
        ToyType.iceCream => 'Ice Cream',
        ToyType.dice => 'Dice',
        ToyType.robot => 'Robot',
        ToyType.basketball => 'Basketball',
        ToyType.flower => 'Flower',
        ToyType.octopus => 'Octopus',
        ToyType.bee => 'Bee',
      };

  /// Stable map from MatchEngine item `type` → screenshot toy visual.
  static ToyType fromGameType(String type) {
    const direct = <String, ToyType>{
      'teddy': ToyType.teddy,
      'duck': ToyType.duck,
      'frog': ToyType.frog,
      'rocket': ToyType.rocket,
      'rabbit': ToyType.rabbit,
      'panda': ToyType.panda,
      'cat': ToyType.cat,
      'owl': ToyType.owl,
      'heart': ToyType.heart,
      'football': ToyType.football,
      'star': ToyType.star,
      'penguin': ToyType.penguin,
      'cactus': ToyType.cactus,
      'grapes': ToyType.grapes,
      'grape': ToyType.grapes,
      'apple': ToyType.apple,
      'car': ToyType.car,
      'chick': ToyType.chick,
      'pig': ToyType.pig,
      'whale': ToyType.whale,
      'unicorn': ToyType.unicorn,
      'dinosaur': ToyType.dinosaur,
      'burger': ToyType.burger,
      'fries': ToyType.fries,
      'sunglasses': ToyType.sunglasses,
      'icecream': ToyType.iceCream,
      'ice_cream': ToyType.iceCream,
      'dice': ToyType.dice,
      'robot': ToyType.robot,
      'basketball': ToyType.basketball,
      'flower': ToyType.flower,
      'octopus': ToyType.octopus,
      'bee': ToyType.bee,
      // Legacy theme-room types → premium toys
      'mug': ToyType.teddy,
      'cup': ToyType.duck,
      'jar': ToyType.frog,
      'cupcake': ToyType.rocket,
      'box': ToyType.rabbit,
      'macaron': ToyType.panda,
      'book': ToyType.cat,
      'candle': ToyType.owl,
      'globe': ToyType.heart,
      'pot': ToyType.cactus,
      'can': ToyType.grapes,
      'seed': ToyType.apple,
      'block': ToyType.rainbowRings,
      'ball': ToyType.football,
      'perfume': ToyType.car,
      'lipstick': ToyType.chick,
      'cream': ToyType.pig,
      'controller': ToyType.whale,
      'cartridge': ToyType.unicorn,
      'headset': ToyType.dinosaur,
      'sauce': ToyType.burger,
      'snack': ToyType.fries,
      'vase': ToyType.flower,
      'frame': ToyType.star,
      'ribbon': ToyType.heart,
      'bag': ToyType.sunglasses,
      'ornament': ToyType.bee,
      'banana': ToyType.chick,
      'bread': ToyType.burger,
      'pizza': ToyType.fries,
      'donut': ToyType.iceCream,
      'water': ToyType.whale,
      'milk': ToyType.penguin,
      'tea': ToyType.owl,
      'wine': ToyType.grapes,
      'beer': ToyType.dice,
      'plant': ToyType.cactus,
      'soap': ToyType.robot,
      'tooth': ToyType.star,
    };
    final hit = direct[type];
    if (hit != null) return hit;
    final values = ToyType.values;
    return values[type.hashCode.abs() % values.length];
  }
}
