# Regenerates lib/ui/widgets/emoji_assets.dart from assets/images/emojis/.
# Type keys drop underscores because GameItem ids are "type_color_nnn" and are
# split on '_'.

$ErrorActionPreference = 'Stop'

$repo = 'd:\Playstore\shelfsortm_master'
$root = Join-Path $repo 'assets\images\emojis'
$out = Join-Path $repo 'lib\ui\widgets\emoji_assets.dart'

$entries = [ordered]@{}
$clashes = @()

foreach ($dir in ([System.IO.Directory]::GetDirectories($root) | Sort-Object)) {
    $cat = Split-Path $dir -Leaf
    foreach ($file in ([System.IO.Directory]::GetFiles($dir) | Sort-Object)) {
        $name = [System.IO.Path]::GetFileName($file)
        $key = ([System.IO.Path]::GetFileNameWithoutExtension($name)) -replace '_', ''
        if ($entries.Contains($key)) { $clashes += $key; continue }
        $entries[$key] = "assets/images/emojis/$cat/$name"
    }
}

if ($clashes.Count -gt 0) {
    throw "Key clashes: $($clashes -join ', ')"
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// GENERATED by tools/gen_emoji_map.ps1 — do not edit by hand.')
[void]$sb.AppendLine()
[void]$sb.AppendLine('/// Maps a [GameItem] type to its emoji artwork.')
[void]$sb.AppendLine('abstract final class EmojiAssets {')
[void]$sb.AppendLine("  /// Shown when a type has no artwork (a '?' mark).")
[void]$sb.AppendLine("  static const String fallback =")
[void]$sb.AppendLine("      'assets/images/emojis/symbols/redquestionmark.png';")
[void]$sb.AppendLine()
[void]$sb.AppendLine('  /// Every emoji type key (all flavors).')
[void]$sb.AppendLine('  static List<String> get allTypes => paths.keys.toList(growable: false);')
[void]$sb.AppendLine()
[void]$sb.AppendLine('  static const Map<String, String> paths = {')
foreach ($key in ($entries.Keys | Sort-Object)) {
    [void]$sb.AppendLine("    '$key': '$($entries[$key])',")
}
[void]$sb.AppendLine('  };')
[void]$sb.AppendLine()
[void]$sb.AppendLine('  static String pathFor(String type) => paths[type] ?? fallback;')
[void]$sb.AppendLine('}')

[System.IO.File]::WriteAllText($out, $sb.ToString())
"wrote $($entries.Count) entries to $out"
